server:
	debug: true
	host: 192.168.33.2
	port: 3000

cyclist:
	ftp: 300
	weight: 61
	frontalArea: 0.47

bike:
	weight: 7
	driveTrainLoss: 0
	tireDiameter: 622
	tireWidth: 23
	cogs: [28, 25, 22, 19, 17, 16, 15, 14, 13, 12, 11, 10]
	chainRings: [34, 50]

physics:
	gravity: 9.8067
	airDensity: 1.226
	